# SPDX-FileCopyrightText: Copyright (c) 2023 - 2024 NVIDIA CORPORATION & AFFILIATES.
# SPDX-FileCopyrightText: All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

defaults :
  - physicsnemo_default
  - arch:
      - fully_connected
  - scheduler: tf_exponential_lr
  - optimizer: adam
  - loss: sum
  - _self_

scheduler:
  decay_rate: 0.95
  decay_steps: 15000

# Write TL checkpoints to a NEW directory (do not overwrite source run)
network_dir : "TEST46_NU-VEL_K1"

# Set this to the trained source checkpoint directory from your 1.5M-step run
# Example (relative): ../aneurysm/network_checkpoint_source
# Example (absolute): /path/to/old/run/network_checkpoint_source
# initialization_network_dir : "/home/ucl/elen/ebarette/src/PhysicsNeMo/outputs/aneurysm/checkpoint_stanford_tl"

training:
  rec_results_freq : 10000
  rec_constraint_freq: 50000
  max_steps : 2500000

batch_size:
  inlet: 700
  outlet: 400
  no_slip: 3000
  interior: 3500
  integral_continuity: 200

custom:
  stl_dir: "./stl_files/0203_k1"

  nu: 0.00025
  inlet_vel: 0.375
  auto_inlet_npoints: 20000
  integral_lambda: 0.2
